# Generated by Django 3.0.3 on 2020-02-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0002_remove_store_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='iva',
            name='iva_porcentaje',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
