# Generated by Django 3.0.3 on 2020-02-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0004_auto_20200224_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterBills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_date', models.DateField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=30)),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_address', models.CharField(max_length=150)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_phone_number', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='StoreBoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_end_date',
            new_name='member_birth_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_sale',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='cash_register_id',
        ),
        migrations.RemoveField(
            model_name='billdetails',
            name='product_discount',
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_birthday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_store',
        ),
        migrations.RemoveField(
            model_name='member',
            name='zona',
        ),
        migrations.AddField(
            model_name='batch',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='price_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_earned_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashregister',
            name='employee_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Zona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_bonus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_pay_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zona',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_cedula',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Bill'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Employee'),
        ),
        migrations.DeleteModel(
            name='CashRegisterIncome',
        ),
        migrations.AddField(
            model_name='storeboss',
            name='boss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Employee'),
        ),
        migrations.AddField(
            model_name='storeboss',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Store'),
        ),
        migrations.AddField(
            model_name='employeestore',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Employee'),
        ),
        migrations.AddField(
            model_name='employeestore',
            name='employee_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Store'),
        ),
        migrations.AddField(
            model_name='cashregisterbills',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Bill'),
        ),
        migrations.AddField(
            model_name='cashregisterbills',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.CashRegister'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Provider'),
            preserve_default=False,
        ),
    ]
