# Generated by Django 3.0.3 on 2020-02-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0004_auto_20200224_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cash_register_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.CashRegister'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Client'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Bill'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Employee'),
        ),
    ]
