# Generated by Django 3.0.3 on 2020-02-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0005_auto_20200228_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
